Refactored modules to hooks
thetayloredman/ProtoBot pull request #110
Opened 2021-01-15 16:49 UTC by LostNuke

**Does this Pull Request fix an issue? If so, please mention the issue.**
#107 

**Describe your changes.**
I refactored Modules to hooks. All that I found, leaving those Modules that were what I suppose meant to be like that (NPM Modules)

**Describe alternatives you've considered**
I used ctrl+f to look for the modules (a lot of code ye know xD)

2021-01-15 17:01 UTC, thetayloredman commented
Well, you need to rename `src/modules/` to `src/hooks/` and rename `templateModule.ts`

2021-01-15 17:01 UTC, thetayloredman requested changes
You need to rename `src/modules/` to `src/hooks/` and rename `templateModule.ts`

2021-01-15 17:04 UTC, LostNuke commented
Whoops didnt see those. Also I accidentally already pushed the uwuify thing forgot it would go into here too xD But yeah issue #98 would be solved too

2021-01-15 17:07 UTC, thetayloredman commented
Fixes #107
Fixes #98

2021-01-15 17:09 UTC, thetayloredman commented
This *should* work, but I need to test.

2021-01-15 17:11 UTC, thetayloredman commented
`src/lib/types/augments.ts` needs to be updated as well

2021-01-15 17:21 UTC, thetayloredman commented
Here's a `git diff` you can apply:

```diff
diff --git a/src/lib/interfaces/Module.ts b/src/lib/interfaces/Module.ts
deleted file mode 100644
index 0b29622..0000000
--- a/src/lib/interfaces/Module.ts
+++ /dev/null
@@ -1,24 +0,0 @@
-/**
- * ProtoBot -- A Discord furry bot
- * Copyright (C) 2020  BadBoyHaloCat
- *
- * This program is free software: you can redistribute it and/or modify
- * it under the terms of the GNU General Public License as published by
- * the Free Software Foundation, either version 3 of the License, or
- * (at your option) any later version.
- *
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- * GNU General Public License for more details.
- *
- * You should have received a copy of the GNU General Public License
- * along with this program.  If not, see <https://www.gnu.org/licenses/>.
- */
-
-import type { Client, Message } from 'discord.js';
-
-export default interface Module {
-    config: { name: string; description: string };
-    run: (client: Client, message: Message, log: (mode: 'i' | 'w' | 'e', message: string) => void) => void;
-}
diff --git a/src/lib/types/Augments.d.ts b/src/lib/types/Augments.d.ts
index 63abff6..6baa796 100644
--- a/src/lib/types/Augments.d.ts
+++ b/src/lib/types/Augments.d.ts
@@ -24,7 +24,7 @@ import Cooldowns from '@lib/interfaces/Cooldowns';
 import Enmap from 'enmap';
 import Fursona from '@lib/interfaces/Fursona';
 import MarkovData from '@lib/interfaces/MarkovData';
-import Module from '@lib/interfaces/Module';
+import Hook from '@lib/interfaces/Hook';
 import UserConfig from '@lib/interfaces/UserConfig';
 import UserStats from '@lib/interfaces/UserStats';
 
@@ -50,7 +50,7 @@ declare module 'discord.js' {
         commands: Enmap<string, Command>;
         commandsConfig: Enmap<string, CommandConfig>; // NOTE: is this redundant?
         commandsRefs: Enmap<string, string>;
-        modules: Enmap<string, Module>;
+        hooks: Enmap<string, Hook>;
 
         // Functions
         public closeDatabases(): void;

```

Put this in a file and then run `git apply path/to/diff.diff` and it'll apply my changes

2021-01-15 17:29 UTC, LostNuke commented
OH right that one confused me speaking of uhh.
![grafik](https://user-images.githubusercontent.com/36674771/104759040-9946dd80-575f-11eb-84a6-a6fe51073f32.png)

2021-01-15 17:52 UTC, thetayloredman commented
> OH right that one confused me speaking of uhh.
> ![grafik](https://user-images.githubusercontent.com/36674771/104759040-9946dd80-575f-11eb-84a6-a6fe51073f32.png)

Apply my patch (add a newline after it if you get corrupt patch at line 26) and it'll fix that

2021-01-15 18:36 UTC, LostNuke commented
Patch has been applied

2021-01-15 18:39 UTC, thetayloredman commented
@Alcremie please take a look at this ok thx

2021-01-16 16:32 UTC, thetayloredman requested changes
A few more things need to be addressed.

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>              log(type, `${chalk.yellow('[')}${chalk.yellow.bold('MODLOAD')}${chalk.yellow(']')} ${message}`);
```suggestion
            log(type, `${chalk.yellow('[')}${chalk.yellow.bold('HOOKLOAD'}${chalk.yellow(']')} ${message}`);
```

`MODLOAD` is "Module Load", not "Hook Load".

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>          l('i', 'Beginning initial module load...');
```suggestion
        l('i', 'Beginning initial hook load...');
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>                          l('i', `Loading module "${modName}"...`);
```suggestion
                        l('i', `Loading hook "${modName}"...`);
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
> +                        const moduleData = require(client.config.dirs.hooks.endsWith('/')
```suggestion
                        const hookData = require(client.config.dirs.hooks.endsWith('/')
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>                          const modName = path.replace('.js', '');
```suggestion
                        const hookName = path.replace('.js', '');
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
> +                        client.hooks.set(modName, moduleData);
```suggestion
                        client.hooks.set(hookName, hookData);
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>                          l('i', `Finished loading module "${modName}"!`);
```suggestion
                        l('i', `Finished loading hook "${hookName}"!`);
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>          log('i', `${chalk.green('[')}${chalk.green.bold('ModuleRunner')}${chalk.green(']')} Running module ${moduleData.config.name}!`);
```suggestion
        log('i', `${chalk.green('[')}${chalk.green.bold('HookRunner')}${chalk.green(']')} Running hook ${hookData.config.name}!`);
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
> +    client.hooks.forEach((moduleData) => {
```suggestion
    client.hooks.forEach((hookData) => {
```

2021-01-16 16:32 UTC, thetayloredman commented on src/index.ts
>          moduleData.run(client, message, log);
```suggestion
        hookData.run(client, message, log);
```

2021-01-16 16:34 UTC, thetayloredman commented
You can batch them you know...

2021-01-16 16:38 UTC, thetayloredman requested changes
Function name too!

2021-01-16 16:38 UTC, thetayloredman commented on src/index.ts
>      function loadMods(): void {
```suggestion
    function loadHooks(): void {
```

Also change line 166 manually (I can't)

2021-01-16 22:58 UTC, thetayloredman approved these changes
LGTM! @Alcremie please review

2021-01-16 23:05 UTC, thetayloredman requested changes

2021-01-16 23:05 UTC, thetayloredman commented on src/index.ts
> +            log(type, `${chalk.yellow('[')}${chalk.yellow.bold('HOOKLOAD'}${chalk.yellow(']')} ${message}`);
```suggestion
            log(type, `${chalk.yellow('[')}${chalk.yellow.bold('HOOKLOAD')}${chalk.yellow(']')} ${message}`);
```

Syntax error

2021-01-16 23:06 UTC, Alcremie reviewed
A few extra things that needed to be considered.

2021-01-16 23:06 UTC, Alcremie commented on src/commands/uwuify.ts
> +    message.channel.send(`${msg}`);
Interpolating `msg` is redundant; it's already a string.
```diff
- message.channel.send(`${msg}`);
+ message.channel.send(msg);
```
There's also really no need to explicitly type either `uwuify` or `msg` in the former lines, but that's beyond the scope of the PR.

2021-01-16 23:06 UTC, Alcremie commented on src/index.ts
> +            log(type, `${chalk.yellow('[')}${chalk.yellow.bold('HOOKLOAD'}${chalk.yellow(']')} ${message}`);
You missed a closing parentheses after `'HOOKLOAD'`.

2021-01-16 23:06 UTC, thetayloredman commented on src/index.ts
> +            log(type, `${chalk.yellow('[')}${chalk.yellow.bold('HOOKLOAD'}${chalk.yellow(']')} ${message}`);
Already pushed that as a hotfix lol

2021-01-16 23:07 UTC, thetayloredman requested changes
My brain is very large

2021-01-16 23:07 UTC, thetayloredman commented on src/index.ts
> +                        l('i', `Loading hook "${modName}"...`);
```suggestion
                        l('i', `Loading hook "${hookName}"...`);
```

2021-01-16 23:09 UTC, thetayloredman approved these changes
Tested it and it appears to work! :clap:

2021-01-16 23:09 UTC, thetayloredman commented
@all-contributors please add @LostNuke for code

2021-01-16 23:11 UTC, thetayloredman commented
@all-contributors please add @Alcremie for maintenance and code

2021-01-16 23:11 UTC, merged