Added new commands.
thetayloredman/ProtoBot pull request #66
Opened 2020-12-06 21:32 UTC by nerdthatnoonelikes

**Does this Pull Request fix an issue? If so, please mention the issue.**
N/A

**Describe your changes.**
What did you change?
Added a meme command, random cat picture command, random dog picture command and a random koala picture command
All of these commands use an external API.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.
N/A
**Additional context**
Add any other context or screenshots about the PR here.

2020-12-06 22:48 UTC, thetayloredman requested changes
These aren't all of my changes, but please resolve these and I'll continue 😄

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/cat.ts
> +import fetch from "node-fetch";
```suggestion
import type { Client, Message } from 'discord.js';
import { MessageEmbed } from 'discord.js';
import fetch from 'node-fetch';
```
It legit scares me how Prettier passed on this...

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/cat.ts
> +    })
```suggestion
    const msg = await message.channel.send("Fetching a cat picture...");
    fetch("https://some-random-api.ml/img/cat")
        .then((res) => res.json())
        .then((body) => {
            let embed = new MessageEmbed()
                .setTitle(`Cat for ${message.author.username}`)
                .setImage(body.link)
                .setTimestamp(Date.now())
                .setColor("RANDOM");
            msg.edit(embed);
    });
```
Prettier fixes

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/cat.ts
> +}
```suggestion
}

```
Add newline at end of file.

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/dog.ts
> +import fetch from "node-fetch";
```suggestion
import type { Client, Message } from 'discord.js';
import { MessageEmbed } from 'discord.js';
import fetch from 'node-fetch';
```

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/dog.ts
> +    })
```suggestion
    const msg = await message.channel.send("Fetching a dog picture...");
    fetch("https://some-random-api.ml/img/dog")
        .then((res) => res.json())
        .then((body) => {
            let embed = new MessageEmbed()
                .setTitle(`Dog for ${message.author.username}`)
                .setImage(body.link)
                .setTimestamp(Date.now())
                .setColor("RANDOM");
            msg.edit(embed);
        });
```

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/dog.ts
> +}
```suggestion
}

```

2020-12-06 22:48 UTC, thetayloredman commented on src/commands/koala.ts
> +import fetch from "node-fetch";
```suggestion
import type { Client, Message } from 'discord.js';
import { MessageEmbed } from 'discord.js';
import fetch from 'node-fetch';
```

2020-12-06 23:07 UTC, thetayloredman requested changes
Looking good so far!

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/cat.ts
> +    fetch("https://some-random-api.ml/img/cat")
```suggestion
    const msg = await message.channel.send('Fetching a cat picture...');
    fetch('https://some-random-api.ml/img/cat')
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/cat.ts
> +                .setColor("RANDOM");
```suggestion
                .setColor('RANDOM');
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/cat.ts
> +    });
```suggestion
        });
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/dog.ts
> +    fetch("https://some-random-api.ml/img/dog")
```suggestion
    const msg = await message.channel.send('Fetching a dog picture...');
    fetch('https://some-random-api.ml/img/dog')
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/dog.ts
> +                .setColor("RANDOM");
```suggestion
                .setColor('RANDOM');
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/koala.ts
> +        .setColor("RANDOM")
```suggestion
    const msg = await message.channel.send('Fetching a koala picture...')
    fetch('https://some-random-api.ml/img/koala')
        .then((res) => res.json())
        .then((body) => {
            let embed = new MessageEmbed()
                .setTitle(`Koala for ${message.author.username}`)
                .setImage(body.link)
                .setTimestamp(Date.now())
                .setColor("RANDOM");
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/koala.ts
> +    })
```suggestion
        msg.delete();
        message.channel.send(embed);
    });
```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/meme.ts
> +}
```suggestion
}

```

2020-12-06 23:07 UTC, thetayloredman commented on src/commands/meme.ts
> +                message.channel.send(embed)
```suggestion
        .then((res) => res.json())
        .then((body) => {
            let embed = new MessageEmbed()
                .setColor("RANDOM")
                .setTitle(body.title)
                .setURL(body.postLink)
                .setImage(body.url)
                .setFooter(`From r/${body.subreddit}`);
            message.channel.send(embed);
```

2020-12-06 23:10 UTC, thetayloredman requested changes
final one i swear

2020-12-06 23:10 UTC, thetayloredman commented on src/commands/koala.ts
> +    const msg = await message.channel.send('Fetching a koala picture...')
```suggestion
    const msg = await message.channel.send('Fetching a koala picture...');
```

2020-12-06 23:10 UTC, thetayloredman commented on src/commands/koala.ts
> +    });
```suggestion
                .setColor('RANDOM');
            msg.delete();
            message.channel.send(embed);
        });
```

2020-12-06 23:10 UTC, thetayloredman commented on src/commands/meme.ts
> +}
```suggestion
// Imports
import type { Client, Message } from 'discord.js';
import { MessageEmbed } from 'discord.js';
import fetch from 'node-fetch';

export function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): void {
    fetch('https://meme-api.herokuapp.com/gimme')
        .then((res) => res.json())
        .then((body) => {
            let embed = new MessageEmbed()
                .setColor('RANDOM')
                .setTitle(body.title)
                .setURL(body.postLink)
                .setImage(body.url)
                .setFooter(`From r/${body.subreddit}`);
            message.channel.send(embed);
        });
}
```

2020-12-06 23:12 UTC, thetayloredman approved these changes
Alright now I'll stop...

2020-12-06 23:22 UTC, Alcremie requested changes
Thanks for opening a PR! I've made a quick glance at your code and have a few suggestions.

2020-12-06 23:22 UTC, Alcremie commented on src/commands/cat.ts
> +import { MessageEmbed } from 'discord.js';
I would rather just import all three from the same module on the same line:
```ts
import { Client, Message, MessageEmbed } from 'discord.js';
```

2020-12-06 23:22 UTC, Alcremie commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
If you're going to be using an explicit `async` function, then you can just use `await`:
```ts
const msg = await message.channel.send('Fetching a cat picture...');
const body = await fetch('https://some-random-api.ml/img/cat').then(res => res.json()).catch(() => null);
if (!body) return message.channel.send('I was unable to retrieve a random cat image.');

const embed = new MessageEmbed()
    .setTitle(`Cat for ${message.author.username}`)
    .setImage(body.link)
    .setTimestamp(Date.now())
    .setColor('RANDOM');
await msg.edit(embed);
```

2020-12-06 23:22 UTC, Alcremie commented on src/commands/dog.ts
> +    fetch('https://some-random-api.ml/img/dog')
See previous comment about using `await` over `fetch().then().then()`.

2020-12-06 23:22 UTC, Alcremie commented on src/commands/dog.ts
> +import { MessageEmbed } from 'discord.js';
Ditto here with the comment about imports.

2020-12-06 23:22 UTC, Alcremie commented on src/commands/koala.ts
> +import { MessageEmbed } from 'discord.js';
Ditto here with the comment about imports.

2020-12-06 23:22 UTC, Alcremie commented on src/commands/koala.ts
> +    fetch('https://some-random-api.ml/img/koala')
See previous comment about using `await` over `fetch().then().then()`.

2020-12-06 23:22 UTC, Alcremie commented on src/commands/meme.ts
> +import { MessageEmbed } from 'discord.js';
Ditto here with the comment about imports.

2020-12-06 23:22 UTC, Alcremie commented on src/commands/meme.ts
> +    fetch('https://meme-api.herokuapp.com/gimme')
For consistency, it might be better to just make this function `async` and use `async`/`await`; however, if you're not going to, you need to at least add ` Promise#catch` handler to your `Promise` chain.

2020-12-06 23:23 UTC, Alcremie commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
While not necessary, it might also be a good idea to make an interface that represents the returned JSON from the API, just so that it's not implicitly `any`.

2020-12-06 23:23 UTC, thetayloredman commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
I'm also seeing that this is with a return type of `Promise<void>`, which isn't actually being returned here, right?

2020-12-06 23:26 UTC, Alcremie commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
An async function without an explicitly returned value has an implied return type of `Promise<void>`, just like a synchronous function without an explicitly returned value has an implicit return type of `void`.

2020-12-06 23:27 UTC, thetayloredman commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
Oh!

2020-12-06 23:29 UTC, thetayloredman commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
https://github.com/thetayloredman/ProtoBot/pull/66#discussion_r537148353

How I would do it:

```ts
interface CatImageData { link: string }
// ...
const body = await fetch('https://some-random-api.ml/img/cat').then(res => res.json()).catch(() => null) as null | CatImageData;
```

@Alcremie did I do this right? lol

2020-12-07 01:27 UTC, Alcremie commented on src/commands/cat.ts
> +export async function run(client: Client, message: Message, args: string[], log: (mode: 'i' | 'w' | 'e', message: string) => void): Promise<void> {
Just from a quick glance, it seems like it would work to me.

2020-12-07 16:31 UTC, thetayloredman commented on src/commands/cat.ts
> +import { MessageEmbed } from 'discord.js';
```suggestion

// Imports
import { Client, Message, MessageEmbed } from 'discord.js';

2020-12-07 16:34 UTC, thetayloredman requested changes
Apply direct suggestions from @Alcremie's review

2020-12-07 16:34 UTC, thetayloredman commented on src/commands/cat.ts
> +import { MessageEmbed } from 'discord.js';
```suggestion
import { Client, Message, MessageEmbed } from 'discord.js';
```

2020-12-07 16:34 UTC, thetayloredman commented on src/commands/cat.ts
> +        });
```suggestion
const msg = await message.channel.send('Fetching a cat picture...');
const body = await fetch('https://some-random-api.ml/img/cat').then(res => res.json()).catch(() => null);
if (!body) return message.channel.send('I was unable to retrieve a random cat image.');

const embed = new MessageEmbed()
    .setTitle(`Cat for ${message.author.username}`)
    .setImage(body.link)
    .setTimestamp(Date.now())
    .setColor('RANDOM');
await msg.edit(embed);
```

https://github.com/thetayloredman/ProtoBot/pull/66/files#r537147570

2020-12-07 16:34 UTC, thetayloredman commented on src/commands/dog.ts
> +import { MessageEmbed } from 'discord.js';
```suggestion
import { Client, Message, MessageEmbed } from 'discord.js';
```

2020-12-07 16:34 UTC, thetayloredman commented on src/commands/koala.ts
> +import { MessageEmbed } from 'discord.js';
```suggestion
import { Client, Message, MessageEmbed } from 'discord.js';
```

2020-12-07 16:34 UTC, thetayloredman commented on src/commands/meme.ts
> +import { MessageEmbed } from 'discord.js';
```suggestion
import { Client, Message, MessageEmbed } from 'discord.js';
```

2020-12-07 16:38 UTC, thetayloredman requested changes
Resolve Alcremie's changes and I'll re-review.

2020-12-12 17:00 UTC, thetayloredman commented
I think I addressed everything?

2020-12-12 18:21 UTC, thetayloredman commented
Merging and then will fix later manually

2020-12-12 18:25 UTC, merged